repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.0"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.17.0"
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.17.0
          - eslint-config-prettier@8.5.0
          - eslint-config-airbnb-base@latest
          - eslint-plugin-import@^2.25.2
